name: CI
on: [push]
jobs:

  build-lnx-mac:
    runs-on: macos-latest

    steps:

    - name: install NDK r21
      run: echo y | sudo -EH "${ANDROID_HOME}/tools/bin/sdkmanager" "ndk;21.3.6528147" >/dev/null
