name: CI
on: [push]
jobs:

  build-ios-app:
    runs-on: macos-latest

    steps:

    - uses: actions/checkout@v2
    - name: env/setup
      run: env/setup.sh
    - name: git submodule
      run: env/submodule.sh --jobs 3

    - name: make iOS .ipa
      run: debug=ldid make -j3 -C app-ios precache='--no-android'


  build-mac-app:
    runs-on: macos-latest

    steps:

    - uses: actions/checkout@v2
    - name: env/setup
      run: env/setup.sh
    - name: git submodule
      run: env/submodule.sh --jobs 3

    - name: make macOS .app
      run: debug=ldid make -j3 -C app-macos precache='--no-android --no-ios --macos'
